export const residentTypes = ["parent", "personal", "rented"];
export const organizations = ["ABC Bank", "XYZ Finance", "Quick Loans", "Credit Hub"];
export const statuses = ["active", "inactive", "blacklisted", "pending"];
export const genders = ["male", "female"];
export const levelOfEducations = ["High School", "Bachelors", "Masters"];
export const employmentStatuses = ["employed", "self-employed", "unemployed"];
export const maritalStatuses = ["married", "single", "divorced", "widowed"];
export const sectorOfEmployments = ["IT", "Finance", "Retail", "N/A"];
export const relationships = ["friend", "brother", "sister", "husband", "wife"];